In [ ]:
import numpy as np 


In [2]:
arreglo = np.array([1, 2, 3, 4, 5])
arreglo 

array([1, 2, 3, 4, 5])

In [3]:
sumado = arreglo + 3
sumado

array([4, 5, 6, 7, 8])

In [4]:
multiplicado = arreglo * 2 
multiplicado

array([ 2,  4,  6,  8, 10])

In [5]:
media = np.mean(arreglo)
media

3.0

In [6]:
x = np.array([3, 6, 9])
y = np.array([7, 4, 6])

sumaArreglos = x + y
print(f"La suma de los arreglos es {sumaArreglos}")

La suma de los arreglos es [10 10 15]
